# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemanager',
            name='id_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
